name: pull-request
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.16.1
      - name: install
        run: yarn bootstrap
      - name: lint
        run: yarn lint
      - name: init-babel-fork
        run: bash scripts/init-babel.sh
      - name: build
        run: yarn build
      - name: test
        run: yarn test
